export const SELECT_PRIMARY_ENTITY = 'SELECT_PRIMARY_ENTITY';
export const DESELECT_PRIMARY_ENTITY = 'DESELECT_PRIMARY_ENTITY';

export const SELECT_SECONDARY_ENTITY = 'SELECT_SECONDARY_ENTITY';
export const DESELECT_SECONDARY_ENTITY = 'DESELECT_SECONDARY_ENTITY';
